#!/bin/sh
module=aesdchar
device=aesdchar
mode="664"
#cd `dirname $0`
set -e
MODULE_PATH=$1
if [ -z "$MODULE_PATH" ]; then
    echo "module path not specified, using current directory"
    MODULE_PATH="."
else
    echo "Using module path: $MODULE_PATH"
fi
# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

if [ -e ${MODULE_PATH}/${module}.ko ]; then
    echo "Loading local built file ${module}.ko"
    insmod ${MODULE_PATH}/$module.ko $* || exit 1
else
    echo "File ${module}.ko not found at path ${MODULE_PATH}"
    #modprobe ${module} || exit 1
fi
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
rm -f /dev/${device}
mknod /dev/${device} c $major 0
chgrp $group /dev/${device}
chmod $mode  /dev/${device}
